name: ShellCheck linting

on:
  pull_request:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          format: tty